url: https://petrknap.github.io

author:
  name: Petr Knap
  web: http://petrknap.cz/
  blog: https://petrknap.github.io/notes/
  rss: https://petrknap.github.io/notes/feed/
  linkedin: https://www.linkedin.com/in/pknap
  github: https://github.com/petrknap
  twitter: https://twitter.com/petrknap

blog:
  lang: en
  title: Petr Knap's Notes
  urls:
    home: /notes/
    issues: https://github.com/petrknap/petrknap.github.io/issues

web:
  menu:
    -
      title: english
      url: //petrknap.github.io/
    -
      title: Äesky
      url: //petrknap.cz/

created_on: 2016
google_analytics_code: UA-88031264-1
permalink: /notes/:year/:month/:day/:title.html
