imports:
  - resource: parameters.yml

framework:
  secret: '%secret%'
  session:
    save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
  http_method_override: true
  trusted_hosts: '%trusted_hosts%'
  assets:
    version: '%assets.version%'
    version_format: '%%s?version=%%s'
  php_errors:
    log: true
  templating:
    engines: ['twig']

twig:
  debug: '%kernel.debug%'
  strict_variables: '%kernel.debug%'

swiftmailer:
  transport: '%swiftmailer.transport%'
  host: '%swiftmailer.host%'
  port: '%swiftmailer.port%'
  encryption: '%swiftmailer.encryption%'
  username: '%swiftmailer.username%'
  password: '%swiftmailer.password%'
  disable_delivery: '%swiftmailer.disable_delivery%'

markdown_web:
  directory: '%kernel.project_dir%/www/'
  site:
    title: Celostní fyzioterapie
    author: Bc. Markéta Schillerová

services:
  AppBundle\Service\OrderProvider:
    arguments:
      - '@session'
      - '@request_stack'
      - '@markdown_web.crawler'
      - '%order_provider.url_prefix%'

order:
  provider: AppBundle\Service\OrderProvider
